### ISSUE TITLE
Request: Option to use unshortened numbers

### ISSUE THREAD

**Issue by yuchingwang** [hibiyasleep/kagerou#101]
After update 3.3.2.257 for ACT, Max Hit/Heal is showing numbers with suffix notation (ie. 4.79K, etc). Could we have an option to toggle if we want to use suffix notation or not?

**Comment by hibiyasleep** [comment]
I updated my ACT to 3.3.3.258 just now, but it was unreproducible for me. ;(

**Comment by Smaugan** [comment]
ACT reverted the change with their most recent update, but I can confirm that numbers were shortened on 3.3.2.257. For example, Midare was showing 43k instead of say 43674.

On 3.3.3.258 it shows the full numbers again.

ACT Changelogs:
![49eb05ea117bf0384d57b56e70d6200e](https://user-images.githubusercontent.com/8088450/49132261-70d79d00-f2d3-11e8-8c90-713da2e9cc00.png)

**Comment by yuchingwang** [comment]
Yeah, with the latest ACT update, this is not really an issue anymore. Closing ticket.
