### ISSUE TITLE
Layout does not recognise Trusts.

### ISSUE THREAD

**Issue by Dajova** [hibiyasleep/kagerou#136]
As seen in the screenshot below, the layout only seems to parse one of the Trust NPCs at any given time and even then, its listed as a chocobo.

![image](https://i.imgur.com/WVc5TF8.png)

I've tried other layouts that has been updated with Shadowbringer and its either your layout or OverlayPlugin that needs to be updated to parse them. Not sure who, but posting on both just in case.

**Comment by hibiyasleep** [comment]
I tried to distinguish them, but data from ACT has no clue about that's a something needs merge, or not; so, I added a filter on merge option, based on theory 'Pets doesn't have job, but Trust NPC does'

* `---` Carbuncle Ruby (Player Name) -> parsed as `acn-pet`, merged.
* `---` Chocobo (Player Name) -> parsed as `chocobo` since name is unknown, merged.
* `RDM` Alisaie (Player Name) -> parsed as `rdm`, not merged.

but... in this case `Ryne` is a trusted NPC right? can you paste here whole overlay data? (via Copy Update Variable button)

ps: I didn't cleared Shadowbringers, i'm lv71 yet. please strike-out things may can be spoiler.

**Comment by Dajova** [comment]
I'm sorry, i'm must be blind.... but i dont find a button like that, neither in the layout or ACT itself. All i could find was the export/import section in the options.

`eyJkIjp7InN0eWxlIjp7ImNvbnRlbnQtYmctY29sb3IiOiJyZ2JhKDAsIDAsIDAsIDAuMykiLCJjb250ZW50LWJnLW9wYWNpdHkiOiIwLjcifSwiY29sd2lkdGgiOnsiX2ktY2xhc3MiOiIzIiwiX2ktb3duZXIiOiIzIiwiX2ktbmFtZSI6IjMiLCJfZGVhbC10b3RhbCI6IjUiLCJfZGVhbC1wZXJfc2Vjb25kIjoiNCIsIl9kZWFsLXBjdCI6IjMiLCJfZGVhbC1zd2luZyI6IjMiLCJfZGVhbC1taXNzIjoiMyIsIl9kZWFsLWhpdGZhaWwiOiIzIiwiX2RlYWwtY3JpdGljYWwiOiIzIiwiX2RlYWwtZGlyZWN0IjoiMyIsIl9kZWFsLWNyaXRfZGlyZWN0IjoiMyIsIl9kZWFsLWNyaXR0eXBlcyI6IjUiLCJfZGVhbC1tYXgiOiIzIiwiX2RlYWwtbWF4aGl0IjoiOSIsIl9kZWFsLW1heHNraWxsIjoiNiIsIl9kZWFsLWxhc3QxMCI6IjQiLCJfZGVhbC1sYXN0MzAiOiI0IiwiX2RlYWwtbGFzdDYwIjoiNCIsIl90YW5rLXRocmVhdF9kZWx0YSI6IjQiLCJfaGVhbC1vdmVyIjoiMyIsIl9oZWFsLW1heCI6IjMifSwidGFicyI6eyIwIjp7ImlkIjoiMCIsImxhYmVsIjoiRFBTIiwid2lkdGgiOiIxIiwic29ydCI6ImRlYWwudG90YWwiLCJjb2wiOlsiaS5pY29uIiwiaS5uYW1lIiwiZGVhbC5wY3QiLCJkZWFsLnBlcl9zZWNvbmQiLCJkZWFsLmNyaXRpY2FsIiwiZGVhbC5kaXJlY3QiLCJkZWFsLmNyaXRfZGlyZWN0IiwiZGVhbC5tYXgiXX0sIjEiOnsiaWQiOiIxIiwibGFiZWwiOiJUYW5rIiwid2lkdGgiOiIxIiwic29ydCI6InRhbmsuZGFtYWdlIiwiY29sIjpbImkuaWNvbiIsImkubmFtZSIsImRlYWwucGVyX3NlY29uZCIsInRhbmsuZGFtYWdlIiwidGFuay5oZWFsIiwidGFuay50aHJlYXRfZGVsdGEiLCJldGMuZGVhdGgiXX0sIjIiOnsiaWQiOiIyIiwibGFiZWwiOiJIZWFsIiwid2lkdGgiOiIxIiwic29ydCI6ImhlYWwudG90YWwiLCJjb2wiOlsiaS5pY29uIiwiaS5uYW1lIiwiaGVhbC5wY3QiLCJoZWFsLnBlcl9zZWNvbmQiLCJoZWFsLnRvdGFsIiwiaGVhbC5vdmVyIiwiaGVhbC5zd2luZyIsImhlYWwubWF4Il19LCIzIjp7ImlkIjoiMyIsImxhYmVsIjoiMjRtIiwid2lkdGgiOiIzIiwic29ydCI6ImRlYWwudG90YWwiLCJjb2wiOlsiaS5pY29uIiwiaS5uYW1lIiwiZGVhbC5sYXN0MzAiXX19fSwiaCI6InN0eWxlLGNvbHdpZHRoLHRhYnN8MTU2Mzk3MzMwMTMxOCJ9`

**Comment by hibiyasleep** [comment]
OK, I just cleared Holminster now, with Trust, this will be fixed very soon. player jobs _was_ overriden while nickname parsing, that determines pet type from it's name.
