### ISSUE TITLE
Two lines header and 'k' before DPS

### ISSUE THREAD

**Issue by LevarioStrix** [hibiyasleep/kagerou#148]
When I de-select the "Narrower Top navigation bar" the location name doesn't display under the mob name.
And the small font after 'k' neither.

**Comment by hibiyasleep** [comment]
![image](https://user-images.githubusercontent.com/5380174/69675014-0a04e380-10e1-11ea-9d98-c71f30a25f73.png)
this is intended appearance, it wasn't made to be rollback older appearance (it's even narrower than old one I except). sorry ;(
CSS customizing may work, but it'll little harder because of changed HTML structure by older updates...

**Comment by LevarioStrix** [comment]
But I don't get the "smaller font" after 1000 and I have the option selected ON.

**Comment by hibiyasleep** [comment]
aah on footer number, that's my mistake. should be fixed in next version.

**Comment by LevarioStrix** [comment]
![image](https://user-images.githubusercontent.com/57450670/69723426-c9758c00-1119-11ea-9a12-4f5573f5f9d1.png)
