### ISSUE TITLE
Support for websocket feature on ngld's OverlayPlugin

### ISSUE THREAD

**Issue by hyskylord** [hibiyasleep/kagerou#156]
Hi,
  In the latest version of OverlayPlugin maintained by ngld, there is a websocket feature added to allow  for streaming overlay windows. It seems the realization is different so I got 404 errors for Kagerou while ACTWebSocket works for me. Is it possible to make Kagerou work on it? Thanks.

**Comment by hibiyasleep** [comment]
did you started `OverlayPlugin WSServer`, or... how did you specified URL in OBS? since it mimics ACTWebSocket, all things should work as same, but there's little differences like SSL support, etc.

**Comment by hyskylord** [comment]
@hibiyasleep I cannot see the exact reason yet but I'm getting 404 errors for OverlayPlugin WSServer. One thing I noticed is the URL for ACTWebSocket is "http://127.0.0.1:10501/github/hibiyasleep/kagerou/overlay/?HOST_PORT=ws://127.0.0.1:10501/", while the URL for OverlayPlugin WSServer is "https://hibiyasleep.github.io/kagerou/overlay/?HOST_PORT=ws://127.0.0.1:10501/", don't know if this is the reason though.

**Comment by hibiyasleep** [comment]
first one will work with ACTWS, but not on OverlayPlugin.
the main problem is: the URL starting with `http://127.0.0.1:10501/` uses ACTWS's internal proxy that implemented as workaround for github pages' https problem. but OverlayPlugin WSServer didn't - and aren't necessary - implemented it.

**Comment by ngld** [comment]
@hyskylord You can use this URL: https://idyllshi.re/kagerou/overlay/?HOST_PORT=ws://127.0.0.1:10501/

OverlayPlugin doesn't implement a reverse proxy (because it's usually not necessary and can cause annoying issues) that's why none of the http://127.0.0.1:10501/github/ URLs will work.
https://hibiyasleep.github.io/kagerou/overlay/?HOST_PORT=ws://127.0.0.1:10501/ redirects to https://hibiya.moe/overlay?HOST_PORT=ws://127.0.0.1:10501/ which returns a 404 error. That's an issue with Kagerou and not something I can fix. For whatever reason, the idyllshi.re URL doesn't redirect and works fine.

@hibiyasleep https://hibiyasleep.github.io/kagerou/overlay/?HOST_PORT=... redirects to 
http://kagerou.hibiya.moe/overlay?HOST_PORT=... but that redirects again to https://hibiya.moe/overlay?HOST_PORT=... is that intentional?

**Comment by hibiyasleep** [comment]
@ngld it was mistake on server configuration, that only occured on IPv6 network which was impossible to reproduce on my home. fixed as of now.

**Comment by hyskylord** [comment]
The OverlayPlugin WSServer URL is now working after the fix.
