### ISSUE TITLE
Kagerou overlay loopback Failed to load

### ISSUE THREAD

**Issue by dlevine3** [hibiyasleep/kagerou#157]
Websocket for Kagerou overlay is not loading on the loopback web address.  I have tried both loopback addresses 127.0.0.1 and IPV6[:::1]

![Failed to load](https://user-images.githubusercontent.com/5386376/78198249-304adf00-7445-11ea-9385-00120968ddb1.jpg)
![ACT settings](https://user-images.githubusercontent.com/5386376/78198251-32ad3900-7445-11ea-9216-4ee2d21628f5.jpg)

**Comment by hibiyasleep** [comment]
I'm assuming it's ACTWS's bug, but there's workaround; please make URL ends with `/`, not with `overlay`.
`http://localhost:10501/github/hibiyasleep/kagerou/overlay/?HOST_PORT=ws://localhost:10501` should work.

other web servers like nginx (I assume it's default with `index` option), GitHub Pages, etc, automatically makes redirection `.../overlay` to `.../overlay/`, since it's basically index page of directory; but ACTWS doesn't.
