### ISSUE TITLE
Overlay OBS Settings

### ISSUE THREAD

**Issue by marti015** [hibiyasleep/kagerou#164]
Hi,

I followed the necessary steps to configure the overlay in OBS.
I am having issues editing the tab info, like it will freeze every time I try to add/remove a column.
Also is copy paste feature disabled on the overlay settings as well during OBS interaction?

**Comment by hibiyasleep** [comment]
fixed with v0.8.5... it seems very naïve, but should work.

when you click `Open Prompt` button, it'll open a small window like this - it makes copy/paste possible.
(* those window might pop under other windows)

![image](https://user-images.githubusercontent.com/5380174/101297251-70335300-386b-11eb-9959-8366d640a4a5.png)
![image](https://user-images.githubusercontent.com/5380174/101297264-7c1f1500-386b-11eb-84ab-eba2d35ce40f.png)
