### ISSUE TITLE
Detect system locale, instead of defaulting to Korean

### ISSUE THREAD

**Issue by jas612** [hibiyasleep/kagerou#40]
If possible, switch default language to same as OS, browser, or some other anchor, instead of defaulting to Korean.  It is a little clunky for English speakers, for example, to find the option in Korean to change to make it English so they can read the menus.  It's not the end of the world if that cannot be done.  Any way to poll the OS for it, or detect the language settings of the browser or browser toolkit that loads it?

Otherwise, this is a stellar piece of work, and using it is an absolute joy.

**Comment by hibiyasleep** [comment]
![image](https://user-images.githubusercontent.com/5380174/27759346-c2d03856-5e69-11e7-9b4b-4cf0688ec27d.png)

This isn't possible as of now, since OverlayPlugin doesn't report system language correctly.

However this may fixed in [next version](https://github.com/hibiyasleep/OverlayPlugin/issues/11).

**Comment by hibiyasleep** [comment]
Fixed with f20247df5a3f61ed3644a3eb2c3b4cfea4831a29, kagerou will try to detect system locale at first launch (or after config reset).
